[languages]
exclude = [
    "HTML",
    "CSS",
    "Makefile",
    "Lua",
    "Shell",
]

[repos]
exclude = [
    "crux-example",
    "dav",
    "dot-manager",
    "dotfiles",
    "hello-bevy",
    "yozhgoor",
    "yozhgoor.github.io"
]
