[languages]
exclude = ["HTML", "CSS", "Makefile"]

[repos]
exclude = [
    "cdoku",
    "crux-example",
    "dav",
    "dot-manager",
    "dotfiles",
    "hello-bevy",
    "todo",
    "yozhgoor",
    "yozhgoor.github.io"
]
